final superHero = <String>[
  'Captain America',
  'Winter Soldier',
  'Nick Fury',
  'Sharon Carter',
  'Hawkeye',
  'Punisher',
  'Crossbones',
  'Red Skull',
  'Spitfire',
  'Beast',
  'Colossus',
  'Cyclops',
  'Emma Frost',
  'Wolverine',
  'X-Men',
  'Hydra',
  'Spider-Man',
  'Iron Man',
  'Sin',
  'Colleen Wing',
  'Misty Knight',
  'Iron Fist',
];
